### PR TITLE
Merge Rory Locals

### PR DESCRIPTION
**Pull request by rozzac90**
Merging some nice functionality from a local betfair wrapper.

 - Move all account and betting endpoints to have params named in method rather than just a params arg.

 - Include doc strings for all account and betting endpoints.

 - Extend enums to cover all betting enums and include doc strings with variable explanations.

 - Extend subscribe_to_orders method to accept orderFilter, usefult for distinguishing order to subscribe to by strategyRef.

 - Add some commonly used methods to utils.

### CODE REVIEW

**Comment by liampauling** [comment]
Hi, 

This is a huge pull request, hopefully I will get some time to review / understand the use of locals, also very keen to add the order filter.

**Comment by rozzac90** [comment]
Hey mate,

Yeah it's fairly huge to be honest haven't done a whole heap of PRs on open source and I know I broke all your tests will get some time to fix them soon hopefully!

Any feedback on it is appreciated.

Cheers
Rory

**Comment by liampauling** [comment]
Making small PR's makes it much easier to merge my side especially if they involve breaking changes. Let me know if you able to split this up.

**Comment by liampauling** [comment]
All now pushed to version 1, thanks!

**Comment by oughtotrade** [comment]
@rozzac90 , do you think you could, with @liampauling 's blessing, cherry-pick out `get_price_increment` and `get_bf_prices` into a separate pull request? They are useful utils to have in the package.

**Pull request closed without merging**
